### PR TITLE
Updating Curl/Git and creating non-root user for brew.sh support

### PR DESCRIPTION
**Pull request by dstamen**
The following was added to /vagrant/all-master

```
yum groupinstall 'Development Tools' -y
rpm -Uvh http://www.city-fan.org/ftp/contrib/yum-repo/rhel6/x86_64/city-fan.org-release-2-1.rhel6.noarch.rpm && yum --enablerepo=city-fan.org install libcurl libcurl-devel -y
adduser portworx
passwd --stdin portworx <<<portworx
usermod -aG wheel portworx
rpm -U http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm && yum install -y git
echo 'source <(kubectl completion bash)' >> /home/portworx/.bashrc
echo 'alias k=kubectl' >> /home/portworx/.bashrc
mkdir /home/portworx/.kube
cp -r /root/.kube/config /home/portworx/.kube/config
```

### CODE REVIEW

**Review by andrewh1978 — CHANGES_REQUESTED** [review]
Apologies in advance for the (constructive) criticism:
1. Please use dnf instead of yum
2. The yum groupinstall on its own adds more than 90 seconds to the provision time of every master node. You probably need to choose which packages are needed rather than taking the whole group. Also we should move this to the scripts directory so it can be pulled in as needed.
3. The city-fan line errored for me with:
Error: Package: libcurl-7.74.0-2.0.cf.rhel7.x86_64 (city-fan.org)
           Requires: libnghttp2.so.14()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
4. This doesn't appear to install brew - is there a step missing?
5. The user stuff should probably go in all-common, probably also worth using the same SSH key as root.

**Comment by dstamen** [comment]
1. ill look
2. yeah its a pre-req for brew on linux. https://docs.brew.sh/Homebrew-on-Linux i think its only needed if you use sudo
3. hmm. that didnt have any issues here but ill look.
4. no i didnt want it to install as it takes 5-10 minutes and not everyone would want to use it
5. possibly, or should we add all the brew stuff as just a template?

**Comment by andrewh1978** [comment]
Put it all in a script, along with the code to install brew. Then the script can be pulled into a template as needed without affecting provision time for anything else.

**Comment by dstamen** [comment]
Im going to cancel this PR as. ill keep it seperate as the goal is to move awayt from brew for PDS

**Pull request closed without merging**
